// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJQH4hTH4_Y5rVHC1ElH4NqR3jicpEXb4',
    appId: '1:234613071605:web:c2f103688993e416682fbc',
    messagingSenderId: '234613071605',
    projectId: 'auth-6bc8b',
    authDomain: 'auth-6bc8b.firebaseapp.com',
    storageBucket: 'auth-6bc8b.appspot.com',
    measurementId: 'G-26ZK5T87ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNs1uXaSQkQWnfdgcHax_cIAR9qv1ePUM',
    appId: '1:234613071605:android:2c02bc18f11f41e7682fbc',
    messagingSenderId: '234613071605',
    projectId: 'auth-6bc8b',
    storageBucket: 'auth-6bc8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19kZE85-I9g4XALg5NOuRkSf_9sUixW0',
    appId: '1:234613071605:ios:4c4a329d2c680297682fbc',
    messagingSenderId: '234613071605',
    projectId: 'auth-6bc8b',
    storageBucket: 'auth-6bc8b.appspot.com',
    iosClientId: '234613071605-sbcchtl0841aiqknfpipl9o4f3tj1g5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19kZE85-I9g4XALg5NOuRkSf_9sUixW0',
    appId: '1:234613071605:ios:4c4a329d2c680297682fbc',
    messagingSenderId: '234613071605',
    projectId: 'auth-6bc8b',
    storageBucket: 'auth-6bc8b.appspot.com',
    iosClientId: '234613071605-sbcchtl0841aiqknfpipl9o4f3tj1g5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
